Merged revisions 66700-66843 via svnmerge from svn+ssh://pythondev@svn.python.org/python/trunk
................
  r66700 | brett.cannon | 2008-10-01 03:46:03 +1000 (Wed, 01 Oct 2008) | 5 lines
  
  Fix a refleak introduced by r66677.
  
  Fix suggested by Amaury Forgeot d'Arc.
  Closes issue #4003.
................
  r66703 | gregory.p.smith | 2008-10-01 06:41:13 +1000 (Wed, 01 Oct 2008) | 6 lines
  
  Works around issue3863: freebsd4/5/6 and os2emx are known to have OS bugs when
  calling fork() from a child thread.  This disables that unit test (with a note
  printed to stderr) on those platforms.
  
  A caveat about buggy platforms is added to the os.fork documentation.
................
  r66708 | andrew.macintyre | 2008-10-01 13:25:25 +1000 (Wed, 01 Oct 2008) | 9 lines
  
  fix for issue 3862: test_array fails FreeBSD 7 amd64
  
  FreeBSD 7's underlying malloc() is behaves differently to earlier versions
  and seriously overcommits available memory on amd64.  This may affect
  other 64bit platforms in some circumstances, so the scale of the 
  problematic test is wound back.
  
  Patch by Mark Dickinson, reviewed by Martin von Loewis.
................
  r66710 | martin.v.loewis | 2008-10-01 21:19:50 +1000 (Wed, 01 Oct 2008) | 2 lines
  
  Bug #3989: Package the 2to3 script (as 2to3.py) in the Windows
  installer.
................
  r66714 | barry.warsaw | 2008-10-02 07:46:40 +1000 (Thu, 02 Oct 2008) | 2 lines
  
  Bumping to 2.6 final.
................
  r66715 | barry.warsaw | 2008-10-02 08:05:43 +1000 (Thu, 02 Oct 2008) | 1 line
  
  Today is the release date
................
  r66721 | barry.warsaw | 2008-10-02 13:33:51 +1000 (Thu, 02 Oct 2008) | 1 line
  
  Bump to 2.7a0
................
  r66722 | martin.v.loewis | 2008-10-02 21:44:17 +1000 (Thu, 02 Oct 2008) | 1 line
  
  Use CRT 9 policy files.
................
  r66739 | christian.heimes | 2008-10-03 04:33:41 +1000 (Fri, 03 Oct 2008) | 1 line
  
  Fixed a comment to C89 style as of http://drj11.wordpress.com/2008/10/02/python-and-bragging-about-c89/
................
  r66744 | benjamin.peterson | 2008-10-03 05:00:31 +1000 (Fri, 03 Oct 2008) | 1 line
  
  we're in 2.7 now
................
  r66745 | georg.brandl | 2008-10-03 05:09:47 +1000 (Fri, 03 Oct 2008) | 2 lines
  
  Forward-port r66736.
................
  r66748 | christian.heimes | 2008-10-03 05:47:50 +1000 (Fri, 03 Oct 2008) | 1 line
  
  Fixed a couple more C99 comments and one occurence of inline.
................
  r66752 | martin.v.loewis | 2008-10-03 06:04:47 +1000 (Fri, 03 Oct 2008) | 2 lines
  
  Add UUID for 2.7.
................
  r66756 | benjamin.peterson | 2008-10-03 06:46:58 +1000 (Fri, 03 Oct 2008) | 1 line
  
  update pydoc topics
................
  r66763 | neal.norwitz | 2008-10-03 14:13:08 +1000 (Fri, 03 Oct 2008) | 1 line
  
  Update the version to 2.7.  Hopefully this fixes the test_distutils failure
................
  r66764 | martin.v.loewis | 2008-10-03 18:59:41 +1000 (Fri, 03 Oct 2008) | 2 lines
  
  Bump version to 2.7. Regenerate.
................
  r66765 | martin.v.loewis | 2008-10-03 20:59:55 +1000 (Fri, 03 Oct 2008) | 1 line
  
  Update version number to 2.7.
................
  r66766 | benjamin.peterson | 2008-10-03 21:52:06 +1000 (Fri, 03 Oct 2008) | 1 line
  
  update the mac installer script
................
  r66767 | andrew.kuchling | 2008-10-03 22:26:42 +1000 (Fri, 03 Oct 2008) | 1 line
  
  Docstring typo.
................
  r66768 | hirokazu.yamamoto | 2008-10-04 02:07:28 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Follows to python's version change (VC6)
................
  r66771 | hirokazu.yamamoto | 2008-10-04 02:18:42 +1000 (Sat, 04 Oct 2008) | 2 lines
  
  Fixed following error when DocXMLRPCServer failed.
    UnboundLocalError: local variable 'serv' referenced before assignment
................
  r66772 | andrew.kuchling | 2008-10-04 02:29:19 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Mention exception in docstring
................
  r66774 | andrew.kuchling | 2008-10-04 02:42:52 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Typo fix
................
  r66776 | hirokazu.yamamoto | 2008-10-04 03:34:49 +1000 (Sat, 04 Oct 2008) | 2 lines
  
  Issue #1706863: Fixed "'NoneType' object has no attribute 'rfind'" error when sqlite libfile not found.
................
  r66783 | andrew.kuchling | 2008-10-04 11:02:29 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Use correct capitalization of NaN
................
  r66784 | andrew.kuchling | 2008-10-04 11:03:42 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Docstring change: Specify exception raised
................
  r66785 | andrew.kuchling | 2008-10-04 11:04:24 +1000 (Sat, 04 Oct 2008) | 1 line
  
  Docstring changes: Specify exceptions raised
................
  r66786 | andrew.kuchling | 2008-10-04 11:05:56 +1000 (Sat, 04 Oct 2008) | 3 lines
  
  Docstring change for *partition: use same tense as other docstrings.
  Hyphenate left- and right-justified.
  Fix 'registerd' typo
................
  r66787 | andrew.kuchling | 2008-10-04 13:08:56 +1000 (Sat, 04 Oct 2008) | 1 line
  
  two corrections
................
  r66790 | andrew.kuchling | 2008-10-05 03:52:01 +1100 (Sun, 05 Oct 2008) | 1 line
  
  Set svn:keywords
................
  r66791 | andrew.kuchling | 2008-10-05 03:52:31 +1100 (Sun, 05 Oct 2008) | 1 line
  
  Add What's New for 2.7
................
  r66792 | benjamin.peterson | 2008-10-05 04:10:14 +1100 (Sun, 05 Oct 2008) | 1 line
  
  silence Sphinx warning
................
  r66793 | georg.brandl | 2008-10-05 05:26:01 +1100 (Sun, 05 Oct 2008) | 2 lines
  
  #4041: don't refer to removed and outdated modules.
................
  r66797 | benjamin.peterson | 2008-10-05 07:55:50 +1100 (Sun, 05 Oct 2008) | 19 lines
  
  Merged revisions 66707,66775,66782 via svnmerge from 
  svn+ssh://pythondev@svn.python.org/sandbox/trunk/2to3/lib2to3
  
  ........
    r66707 | benjamin.peterson | 2008-09-30 18:27:10 -0500 (Tue, 30 Sep 2008) | 1 line
    
    fix #4001: fix_imports didn't check for __init__.py before converting to relative imports
  ........
    r66775 | collin.winter | 2008-10-03 12:08:26 -0500 (Fri, 03 Oct 2008) | 4 lines
    
    Add an alternative iterative pattern matching system that, while slower, correctly parses files that cause the faster recursive pattern matcher to fail with a recursion error. lib2to3 falls back to the iterative matcher if the recursive one fails.
    
    Fixes http://bugs.python.org/issue2532. Thanks to Nick Edds.
  ........
    r66782 | benjamin.peterson | 2008-10-03 17:51:36 -0500 (Fri, 03 Oct 2008) | 1 line
    
    add Victor Stinner's fixer for os.getcwdu -> os.getcwd #4023
  ........
................
  r66801 | andrew.kuchling | 2008-10-05 08:51:59 +1100 (Sun, 05 Oct 2008) | 1 line
  
  Punctuation fix; expand dict.update docstring to be clearer
................
  r66803 | benjamin.peterson | 2008-10-05 09:15:31 +1100 (Sun, 05 Oct 2008) | 1 line
  
  fix typo
................
  r66804 | andrew.kuchling | 2008-10-05 11:11:56 +1100 (Sun, 05 Oct 2008) | 1 line
  
  #1415508 from Rocky Bernstein: add docstrings for enable_interspersed_args(), disable_interspersed_args()
................
  r66809 | hirokazu.yamamoto | 2008-10-06 12:57:03 +1100 (Mon, 06 Oct 2008) | 1 line
  
  Added the test for issue3762.
................
  r66810 | hirokazu.yamamoto | 2008-10-06 13:41:59 +1100 (Mon, 06 Oct 2008) | 1 line
  
  More strict test. Consider the case sys.executable itself is symlink.
................
  r66813 | andrew.kuchling | 2008-10-06 23:07:04 +1100 (Mon, 06 Oct 2008) | 3 lines
  
  Per Greg Ward, optparse is no longer being externally maintained.
  I'll look at the bugs in the Optik bug tracker and copy them to the Python bug
  tracker if they're still relevant.
................
  r66814 | martin.v.loewis | 2008-10-07 02:15:40 +1100 (Tue, 07 Oct 2008) | 3 lines
  
  Issue #4014: Don't claim that Python has an Alpha release status, in addition
  to claiming it is Mature.
................
  r66819 | brett.cannon | 2008-10-07 09:44:37 +1100 (Tue, 07 Oct 2008) | 4 lines
  
  Add the 'patchcheck' build target to .PHONY.
  
  Re-closes issue 3758. Thanks to Ralph Corderoy for the catch.
................
  r66822 | skip.montanaro | 2008-10-07 12:55:20 +1100 (Tue, 07 Oct 2008) | 2 lines
  
  Simplify individual tests by defining setUp and tearDown methods.
................
  r66823 | skip.montanaro | 2008-10-07 13:02:00 +1100 (Tue, 07 Oct 2008) | 2 lines
  
  Pay attention to -R entries in LDFLAGS.
................
  r66832 | skip.montanaro | 2008-10-08 02:03:40 +1100 (Wed, 08 Oct 2008) | 1 line
  
  save/restore stdout/stderr instead of relying on __*__ versions
................
  r66835 | hirokazu.yamamoto | 2008-10-08 05:10:47 +1100 (Wed, 08 Oct 2008) | 1 line
  
  more intensive test on dbm.
................
  r66836 | amaury.forgeotdarc | 2008-10-08 07:32:10 +1100 (Wed, 08 Oct 2008) | 5 lines
  
  #4069: aSet.remove(otherSet) would always report the empty frozenset([]) as the missing key.
  Now it correctly refers to the initial otherset.
  
  Reviewed by Raymond. Will backport to 2.6.
................