test_descr is failing because e.g.
>>> a = object()
>>> a.foo = 12
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
TypeError: 'object' object has only read-only attributes (assign to .foo)
>>>

now but raised AttributeError before.  I'm not sure which is better, but
I want to merge the trunk into the branch again now so have a short-term
but intense <wink> interest in just having all tests pass first.