WindowsError_new():  Removed needless initializations.
Richard & Georg:  this is in fact where the

     "an integer is required"

error is coming from, via the WindowsError_new line:

    errcode = PyInt_AsLong(self->myerrno);

self->myerrno is Py_None at this point, so
PyInt_AsLong() complains.

It looks like the function being called at the time
was ntpath.isfile.  Knowing that, I can reproduce it
easily:

>>> import os.path
[27025 refs]
>>> os.path.isfile('abc')
False
XXX undetected error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required

Note the "XXX undetected error"!  That comes out of
ceval.c.  Your turn ;-)